import { task } from "hardhat/config";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import * as fs from "fs";
import * as path from "path";

task(
  "deploy:full",
  "Deploy all CovertMRV contracts: CapRegistry + CapCheck + ComplianceCertificate + " +
    "SupplierAttest + ProductFootprint + cCO2 + CreditIssuer + CreditRetire, " +
    "wire them, and write addresses + ABIs to the frontend"
).setAction(async (_, hre: HardhatRuntimeEnvironment) => {
  const { ethers, network } = hre;

  console.log(`\n▶ Deploying CovertMRV full stack to ${network.name}...`);
  const [deployer] = await ethers.getSigners();
  console.log(`  deployer: ${deployer.address}`);
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`  balance:  ${ethers.formatEther(balance)} ETH\n`);

  // ─── Core contracts ─────────────────────────────────────────────────

  const Registry = await ethers.getContractFactory("CapRegistry");
  const registry = await Registry.deploy();
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log(`✓ CapRegistry              → ${registryAddress}`);

  const Check = await ethers.getContractFactory("CapCheck");
  const check = await Check.deploy(registryAddress);
  await check.waitForDeployment();
  const checkAddress = await check.getAddress();
  console.log(`✓ CapCheck                 → ${checkAddress}`);

  const Cert = await ethers.getContractFactory("ComplianceCertificate");
  const cert = await Cert.deploy();
  await cert.waitForDeployment();
  const certAddress = await cert.getAddress();
  console.log(`✓ ComplianceCertificate    → ${certAddress}`);

  await (await cert.setCapCheck(checkAddress)).wait();
  await (await check.setCertificate(certAddress)).wait();
  console.log(`✓ Wired: cert.setCapCheck + check.setCertificate`);

  // ─── Supply chain ───────────────────────────────────────────────────

  const SupplierAttest = await ethers.getContractFactory("SupplierAttest");
  const supplierAttest = await SupplierAttest.deploy();
  await supplierAttest.waitForDeployment();
  const supplierAttestAddress = await supplierAttest.getAddress();
  console.log(`✓ SupplierAttest           → ${supplierAttestAddress}`);

  const ProductFootprint = await ethers.getContractFactory("ProductFootprint");
  const productFootprint = await ProductFootprint.deploy(supplierAttestAddress);
  await productFootprint.waitForDeployment();
  const productFootprintAddress = await productFootprint.getAddress();
  console.log(`✓ ProductFootprint         → ${productFootprintAddress}`);

  // ─── Carbon credits ─────────────────────────────────────────────────

  const CcCO2 = await ethers.getContractFactory("cCO2");
  const cco2 = await CcCO2.deploy();
  await cco2.waitForDeployment();
  const cco2Address = await cco2.getAddress();
  console.log(`✓ cCO2                     → ${cco2Address}`);

  const CreditIssuer = await ethers.getContractFactory("CreditIssuer");
  const creditIssuer = await CreditIssuer.deploy(checkAddress, cco2Address);
  await creditIssuer.waitForDeployment();
  const creditIssuerAddress = await creditIssuer.getAddress();
  console.log(`✓ CreditIssuer             → ${creditIssuerAddress}`);

  const CreditRetire = await ethers.getContractFactory("CreditRetire");
  const creditRetire = await CreditRetire.deploy(cco2Address);
  await creditRetire.waitForDeployment();
  const creditRetireAddress = await creditRetire.getAddress();
  console.log(`✓ CreditRetire             → ${creditRetireAddress}`);

  // ─── Wiring ─────────────────────────────────────────────────────────

  await (await cco2.setIssuer(creditIssuerAddress)).wait();
  await (await cco2.setRetirer(creditRetireAddress)).wait();
  console.log(`✓ cCO2.setIssuer + cCO2.setRetirer`);

  await (await check.setCreditIssuer(creditIssuerAddress)).wait();
  console.log(`✓ CapCheck.setCreditIssuer`);

  // ─── Write artifacts ────────────────────────────────────────────────

  const chainId = Number((await ethers.provider.getNetwork()).chainId);

  const registryArtifact = await hre.artifacts.readArtifact("CapRegistry");
  const checkArtifact = await hre.artifacts.readArtifact("CapCheck");
  const certArtifact = await hre.artifacts.readArtifact("ComplianceCertificate");
  const supplierAttestArtifact = await hre.artifacts.readArtifact("SupplierAttest");
  const productFootprintArtifact = await hre.artifacts.readArtifact("ProductFootprint");
  const cco2Artifact = await hre.artifacts.readArtifact("cCO2");
  const creditIssuerArtifact = await hre.artifacts.readArtifact("CreditIssuer");
  const creditRetireArtifact = await hre.artifacts.readArtifact("CreditRetire");

  const frontendConfig = path.resolve(
    __dirname,
    "..",
    "frontend",
    "src",
    "config",
    "contracts.ts"
  );
  fs.mkdirSync(path.dirname(frontendConfig), { recursive: true });

  const fileBody = `// AUTOGENERATED by tasks/deployFull.ts — do not edit by hand.
// Run \`npx hardhat deploy:full --network arb-sepolia\` from the repo root to regenerate.

export const CHAIN_ID = ${chainId};

const ADDR = /^0x[a-fA-F0-9]{40}$/;

/** Vercel often sets VITE_* to "" — empty string must fall back to baked-in deploy addresses. */
function viteAddress(envKey: string, fallback: \`0x\${string}\`): \`0x\${string}\` {
  const raw = import.meta.env[envKey] as string | undefined;
  if (typeof raw === "string" && ADDR.test(raw.trim())) {
    return raw.trim() as \`0x\${string}\`;
  }
  return fallback;
}

export const CAP_REGISTRY_ADDRESS = viteAddress(
  "VITE_CAP_REGISTRY_ADDRESS",
  "${registryAddress}" as \`0x\${string}\`,
);

export const CAP_CHECK_ADDRESS = viteAddress(
  "VITE_CAP_CHECK_ADDRESS",
  "${checkAddress}" as \`0x\${string}\`,
);

export const COMPLIANCE_CERTIFICATE_ADDRESS = viteAddress(
  "VITE_COMPLIANCE_CERTIFICATE_ADDRESS",
  "${certAddress}" as \`0x\${string}\`,
);

export const SUPPLIER_ATTEST_ADDRESS = viteAddress(
  "VITE_SUPPLIER_ATTEST_ADDRESS",
  "${supplierAttestAddress}" as \`0x\${string}\`,
);

export const PRODUCT_FOOTPRINT_ADDRESS = viteAddress(
  "VITE_PRODUCT_FOOTPRINT_ADDRESS",
  "${productFootprintAddress}" as \`0x\${string}\`,
);

export const CCO2_ADDRESS = viteAddress(
  "VITE_CCO2_ADDRESS",
  "${cco2Address}" as \`0x\${string}\`,
);

export const CREDIT_ISSUER_ADDRESS = viteAddress(
  "VITE_CREDIT_ISSUER_ADDRESS",
  "${creditIssuerAddress}" as \`0x\${string}\`,
);

export const CREDIT_RETIRE_ADDRESS = viteAddress(
  "VITE_CREDIT_RETIRE_ADDRESS",
  "${creditRetireAddress}" as \`0x\${string}\`,
);

export const CAP_REGISTRY_ABI = ${JSON.stringify(registryArtifact.abi, null, 2)} as const;
export const CAP_CHECK_ABI = ${JSON.stringify(checkArtifact.abi, null, 2)} as const;
export const COMPLIANCE_CERTIFICATE_ABI = ${JSON.stringify(certArtifact.abi, null, 2)} as const;
export const SUPPLIER_ATTEST_ABI = ${JSON.stringify(supplierAttestArtifact.abi, null, 2)} as const;
export const PRODUCT_FOOTPRINT_ABI = ${JSON.stringify(productFootprintArtifact.abi, null, 2)} as const;
export const CCO2_ABI = ${JSON.stringify(cco2Artifact.abi, null, 2)} as const;
export const CREDIT_ISSUER_ABI = ${JSON.stringify(creditIssuerArtifact.abi, null, 2)} as const;
export const CREDIT_RETIRE_ABI = ${JSON.stringify(creditRetireArtifact.abi, null, 2)} as const;
`;
  fs.writeFileSync(frontendConfig, fileBody);
  console.log(`\n✓ Wrote ${path.relative(process.cwd(), frontendConfig)}`);

  const deploymentsPath = path.resolve(__dirname, "..", "deployments.json");
  let history: Record<string, unknown> = {};
  if (fs.existsSync(deploymentsPath)) {
    try {
      history = JSON.parse(fs.readFileSync(deploymentsPath, "utf8"));
    } catch {
      history = {};
    }
  }
  history[network.name] = {
    chainId,
    deployer: deployer.address,
    capRegistry: registryAddress,
    capCheck: checkAddress,
    complianceCertificate: certAddress,
    supplierAttest: supplierAttestAddress,
    productFootprint: productFootprintAddress,
    cco2: cco2Address,
    creditIssuer: creditIssuerAddress,
    creditRetire: creditRetireAddress,
    timestamp: new Date().toISOString(),
  };
  fs.writeFileSync(deploymentsPath, JSON.stringify(history, null, 2));
  console.log(`✓ Updated deployments.json`);

  console.log(`\n✅ Full stack deployment complete!`);
  console.log(`   CapRegistry:           ${registryAddress}`);
  console.log(`   CapCheck:              ${checkAddress}`);
  console.log(`   ComplianceCertificate: ${certAddress}`);
  console.log(`   SupplierAttest:        ${supplierAttestAddress}`);
  console.log(`   ProductFootprint:      ${productFootprintAddress}`);
  console.log(`   cCO2:                  ${cco2Address}`);
  console.log(`   CreditIssuer:          ${creditIssuerAddress}`);
  console.log(`   CreditRetire:          ${creditRetireAddress}`);
  console.log(`\nNext steps:`);
  console.log(`  1. npx hardhat covertmrv:set-cap --network ${network.name} --company <addr> --cap 50000`);
  console.log(`  2. npx hardhat covertmrv:grant-role --network ${network.name} --account <addr> --role 1`);
  console.log(`  3. cd frontend && npm run build`);
});
