import { task } from "hardhat/config";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import * as fs from "fs";
import * as path from "path";

task(
  "deploy:covertmrv",
  "Deploy CapRegistry + CapCheck and write addresses + ABIs to the frontend"
).setAction(async (_, hre: HardhatRuntimeEnvironment) => {
  const { ethers, network } = hre;

  console.log(`\n▶ Deploying CovertMRV to ${network.name}...`);
  const [deployer] = await ethers.getSigners();
  console.log(`  deployer: ${deployer.address}`);
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`  balance:  ${ethers.formatEther(balance)} ETH\n`);

  // 1. CapRegistry
  const Registry = await ethers.getContractFactory("CapRegistry");
  const registry = await Registry.deploy();
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log(`✓ CapRegistry → ${registryAddress}`);

  // 2. CapCheck
  const Check = await ethers.getContractFactory("CapCheck");
  const check = await Check.deploy(registryAddress);
  await check.waitForDeployment();
  const checkAddress = await check.getAddress();
  console.log(`✓ CapCheck    → ${checkAddress}`);

  // 3. Write to frontend config + a deployments.json record.
  const chainId = Number((await ethers.provider.getNetwork()).chainId);

  const registryArtifact = await hre.artifacts.readArtifact("CapRegistry");
  const checkArtifact = await hre.artifacts.readArtifact("CapCheck");

  const frontendConfig = path.resolve(
    __dirname,
    "..",
    "frontend",
    "src",
    "config",
    "contracts.ts"
  );
  fs.mkdirSync(path.dirname(frontendConfig), { recursive: true });

  const fileBody = `// AUTOGENERATED by tasks/deploy.ts — do not edit by hand.
// Run \`npm run deploy:arb\` from the repo root to regenerate.

export const CHAIN_ID = ${chainId};

export const CAP_REGISTRY_ADDRESS =
  (import.meta.env.VITE_CAP_REGISTRY_ADDRESS as \`0x\${string}\` | undefined) ??
  ("${registryAddress}" as \`0x\${string}\`);

export const CAP_CHECK_ADDRESS =
  (import.meta.env.VITE_CAP_CHECK_ADDRESS as \`0x\${string}\` | undefined) ??
  ("${checkAddress}" as \`0x\${string}\`);

export const CAP_REGISTRY_ABI = ${JSON.stringify(
    registryArtifact.abi,
    null,
    2
  )} as const;

export const CAP_CHECK_ABI = ${JSON.stringify(checkArtifact.abi, null, 2)} as const;
`;
  fs.writeFileSync(frontendConfig, fileBody);
  console.log(`\n✓ Wrote ${path.relative(process.cwd(), frontendConfig)}`);

  const deploymentsPath = path.resolve(__dirname, "..", "deployments.json");
  let history: Record<string, unknown> = {};
  if (fs.existsSync(deploymentsPath)) {
    try {
      history = JSON.parse(fs.readFileSync(deploymentsPath, "utf8"));
    } catch {
      history = {};
    }
  }
  history[network.name] = {
    chainId,
    deployer: deployer.address,
    capRegistry: registryAddress,
    capCheck: checkAddress,
    timestamp: new Date().toISOString(),
  };
  fs.writeFileSync(deploymentsPath, JSON.stringify(history, null, 2));
  console.log(`✓ Updated deployments.json`);

  console.log(`\nNext steps:`);
  console.log(`  1. npx hardhat covertmrv:set-cap --network ${network.name} --company ${deployer.address} --cap 50000`);
  console.log(`  2. cd frontend && npm install && npm run dev`);
});
